### PR TITLE
Fix delete commands not cascading to tutorial teams

### LINKED ISSUE #143: Fixing "Help" to link to Team repo user guide

### PR DESCRIPTION
**Pull request by whelan-low**
This PR introduces a small fix to DeleteStudentCommand and DeleteStudentFromClass commands to make it cascade to the tutorial teams involved.

Also fixes #143

TODO:
- [x] Add test cases

### CODE REVIEW

File: src/test/java/seedu/address/model/module/TutorialClassTest.java [hunk 1]
```diff
@@ -187,4 +187,39 @@ void deleteStudent_inList_success() {
...
+    @Test
+    void deleteStudentFromTeams_success() {
+        ArrayList<Person> students = new ArrayList<>();
+
+        // Creating Person object
+        Name name1 = new Name("John");
+        Email email1 = new Email("john@example.com");
+        StudentId stuId1 = new StudentId("A0213333J");
+        Set<Tag> tags1 = new HashSet<>();
+        Person student1 = new Person(name1, email1, stuId1, tags1);
```
Comment (Zack-Tay) [inline src/test/java/seedu/address/model/module/TutorialClassTest.java:200]: Is this necessary? There is a person builder class to help you with that, I think it would be better to use that

File: src/test/java/seedu/address/model/module/TutorialClassTest.java [hunk 2]
```diff
@@ -187,4 +187,39 @@ void deleteStudent_inList_success() {
...
+        //both teams should have 1 person
+        assertEquals(1, tutorialClass.getTutorialTeam(tutorialClass, team1).getStudents().size());
+        assertEquals(1, tutorialClass.getTutorialTeam(tutorialClass, team2).getStudents().size());
+
+        //delete the student from all teams
+        tutorialClass.deleteStudentFromTeams(student1);
+
+        //both teams should now be empty (i.e. 0 people)
+        assertEquals(0, tutorialClass.getTutorialTeam(tutorialClass, team1).getStudents().size());
+        assertEquals(0, tutorialClass.getTutorialTeam(tutorialClass, team2).getStudents().size());
```
Comment (Zack-Tay) [inline src/test/java/seedu/address/model/module/TutorialClassTest.java:223]: I think the use of magic numbers here is not very good? you can create a variable that describes the number that would be better! thanks.

File: src/test/java/seedu/address/model/module/TutorialClassTest.java [hunk 3]
```diff
@@ -187,4 +187,39 @@ void deleteStudent_inList_success() {
...
+        Set<Tag> tags1 = new HashSet<>();
+        Person student1 = new Person(name1, email1, stuId1, tags1);
+
+        students.add(student1);
+
+        TutorialClass tutorialClass = new TutorialClass(VALID_TUTORIAL, students);
+
+        // Create teams, add student to teams, and add teams to tutorial class
+        TutorialTeam team1 = new TutorialTeam("a");
+        TutorialTeam team2 = new TutorialTeam("b");
```
Comment (Zack-Tay) [inline src/test/java/seedu/address/model/module/TutorialClassTest.java:208]: there are valid team names in the command util class to use, you may want to use that instead!

Comment (whelan-low) [reply src/test/java/seedu/address/model/module/TutorialClassTest.java:208]: Alright, will update

File: src/test/java/seedu/address/model/module/TutorialClassTest.java (hunk 2 above)
Comment (whelan-low) [reply src/test/java/seedu/address/model/module/TutorialClassTest.java:223]: Thought the comment would be enough to explain the numbers used, but I can still see the issue.

Thanks for the check!

File: src/test/java/seedu/address/model/module/TutorialClassTest.java (hunk 1 above)
Comment (whelan-low) [reply src/test/java/seedu/address/model/module/TutorialClassTest.java:200]: Alright, will update

**Review by mahadhir247 — APPROVED** [review]
LGTM!
